#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 94
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 6

enum {
  anon_sym_LF = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_PLUS = 4,
  anon_sym_DASH = 5,
  anon_sym_STAR = 6,
  anon_sym_SLASH = 7,
  sym_number = 8,
  anon_sym_DQUOTE = 9,
  sym_unescaped_string_fragment = 10,
  anon_sym_LBRACE = 11,
  anon_sym_COMMA = 12,
  anon_sym_RBRACE = 13,
  anon_sym_COLON = 14,
  anon_sym_DOT = 15,
  anon_sym_fun = 16,
  anon_sym_val = 17,
  anon_sym_EQ = 18,
  sym_identifier = 19,
  sym_source_file = 20,
  sym__statement = 21,
  sym_expression_statement = 22,
  sym__expression = 23,
  sym_unary_expression = 24,
  sym_binary_expression = 25,
  sym_string = 26,
  sym_object_expression = 27,
  sym_object_property = 28,
  sym__property_key = 29,
  sym_member_expression = 30,
  sym_call_expression = 31,
  sym_call_arguments = 32,
  sym_function_declaration = 33,
  sym_function_parameters = 34,
  sym_variable_declaration = 35,
  sym_block = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_string_repeat1 = 38,
  aux_sym_object_expression_repeat1 = 39,
  aux_sym_call_arguments_repeat1 = 40,
  aux_sym_function_parameters_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_unescaped_string_fragment] = "unescaped_string_fragment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_fun] = "fun",
  [anon_sym_val] = "val",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_string] = "string",
  [sym_object_expression] = "object_expression",
  [sym_object_property] = "object_property",
  [sym__property_key] = "_property_key",
  [sym_member_expression] = "member_expression",
  [sym_call_expression] = "call_expression",
  [sym_call_arguments] = "call_arguments",
  [sym_function_declaration] = "function_declaration",
  [sym_function_parameters] = "function_parameters",
  [sym_variable_declaration] = "variable_declaration",
  [sym_block] = "block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_object_expression_repeat1] = "object_expression_repeat1",
  [aux_sym_call_arguments_repeat1] = "call_arguments_repeat1",
  [aux_sym_function_parameters_repeat1] = "function_parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_unescaped_string_fragment] = sym_unescaped_string_fragment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_string] = sym_string,
  [sym_object_expression] = sym_object_expression,
  [sym_object_property] = sym_object_property,
  [sym__property_key] = sym__property_key,
  [sym_member_expression] = sym_member_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_call_arguments] = sym_call_arguments,
  [sym_function_declaration] = sym_function_declaration,
  [sym_function_parameters] = sym_function_parameters,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_block] = sym_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_object_expression_repeat1] = aux_sym_object_expression_repeat1,
  [aux_sym_call_arguments_repeat1] = aux_sym_call_arguments_repeat1,
  [aux_sym_function_parameters_repeat1] = aux_sym_function_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_unescaped_string_fragment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_object_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_object_property] = {
    .visible = true,
    .named = true,
  },
  [sym__property_key] = {
    .visible = false,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_expr = 1,
  field_function = 2,
  field_key = 3,
  field_lhs = 4,
  field_object = 5,
  field_op = 6,
  field_property = 7,
  field_receiver = 8,
  field_rhs = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_expr] = "expr",
  [field_function] = "function",
  [field_key] = "key",
  [field_lhs] = "lhs",
  [field_object] = "object",
  [field_op] = "op",
  [field_property] = "property",
  [field_receiver] = "receiver",
  [field_rhs] = "rhs",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
  [4] = {.index = 7, .length = 2},
  [5] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expr, 1},
    {field_op, 0},
  [2] =
    {field_lhs, 0},
    {field_op, 1},
    {field_rhs, 2},
  [5] =
    {field_object, 0},
    {field_property, 2},
  [7] =
    {field_key, 0},
    {field_value, 2},
  [9] =
    {field_function, 2},
    {field_receiver, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 15,
  [16] = 9,
  [17] = 15,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 25,
  [36] = 28,
  [37] = 18,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 29,
  [42] = 32,
  [43] = 27,
  [44] = 44,
  [45] = 33,
  [46] = 20,
  [47] = 47,
  [48] = 30,
  [49] = 23,
  [50] = 31,
  [51] = 22,
  [52] = 24,
  [53] = 26,
  [54] = 34,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 55,
  [61] = 56,
  [62] = 57,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 58,
  [69] = 65,
  [70] = 70,
  [71] = 71,
  [72] = 63,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 80,
  [90] = 90,
  [91] = 91,
  [92] = 86,
  [93] = 93,
};

static inline bool sym_identifier_character_set_1(int32_t c) {
  return (c < 160
    ? (c < '['
      ? (c < 0
        ? c == 0
        : (c <= '#' || (c >= '%' && c <= '@')))
      : (c <= '^' || (c < '|'
        ? c == '`'
        : c <= '~')))
    : (c <= 160 || (c < 8287
      ? (c < 8192
        ? c == 5760
        : (c <= 8203 || c == 8239))
      : (c <= 8288 || (c < 65279
        ? c == 12288
        : c <= 65279)))));
}

static inline bool sym_identifier_character_set_2(int32_t c) {
  return (c < 160
    ? (c < ':'
      ? (c < 0
        ? c == 0
        : (c <= '#' || (c >= '%' && c <= '/')))
      : (c <= '@' || (c < '`'
        ? (c >= '[' && c <= '^')
        : (c <= '`' || (c >= '{' && c <= '~')))))
    : (c <= 160 || (c < 8287
      ? (c < 8192
        ? c == 5760
        : (c <= 8203 || c == 8239))
      : (c <= 8288 || (c < 65279
        ? c == 12288
        : c <= 65279)))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == ':') ADVANCE(26);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'f') ADVANCE(34);
      if (lookahead == 'v') ADVANCE(31);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (!sym_identifier_character_set_1(lookahead)) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (!sym_identifier_character_set_1(lookahead)) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '{') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_unescaped_string_fragment);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_unescaped_string_fragment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_fun);
      if (lookahead == '\\') ADVANCE(4);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_val);
      if (lookahead == '\\') ADVANCE(4);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'a') ADVANCE(32);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(29);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(28);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'u') ADVANCE(33);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(88),
    [sym__statement] = STATE(5),
    [sym_expression_statement] = STATE(92),
    [sym__expression] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym_string] = STATE(44),
    [sym_object_expression] = STATE(44),
    [sym_member_expression] = STATE(44),
    [sym_call_expression] = STATE(44),
    [sym_function_declaration] = STATE(92),
    [sym_variable_declaration] = STATE(92),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_fun] = ACTIONS(13),
    [anon_sym_val] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      sym_number,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(36), 1,
      anon_sym_val,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(92), 3,
      sym_expression_statement,
      sym_function_declaration,
      sym_variable_declaration,
    STATE(44), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [44] = 11,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(24), 1,
      sym_number,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(36), 1,
      anon_sym_val,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(3), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(86), 3,
      sym_expression_statement,
      sym_function_declaration,
      sym_variable_declaration,
    STATE(44), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [88] = 11,
    ACTIONS(7), 1,
      sym_number,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fun,
    ACTIONS(15), 1,
      anon_sym_val,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(3), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(86), 3,
      sym_expression_statement,
      sym_function_declaration,
      sym_variable_declaration,
    STATE(44), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [132] = 11,
    ACTIONS(7), 1,
      sym_number,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fun,
    ACTIONS(15), 1,
      anon_sym_val,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(92), 3,
      sym_expression_statement,
      sym_function_declaration,
      sym_variable_declaration,
    STATE(44), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [176] = 11,
    ACTIONS(7), 1,
      sym_number,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fun,
    ACTIONS(15), 1,
      anon_sym_val,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(4), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(86), 3,
      sym_expression_statement,
      sym_function_declaration,
      sym_variable_declaration,
    STATE(44), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [220] = 6,
    ACTIONS(48), 1,
      anon_sym_RPAREN,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(52), 2,
      sym_number,
      sym_identifier,
    STATE(25), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [247] = 6,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(60), 2,
      sym_number,
      sym_identifier,
    STATE(35), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [274] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(62), 2,
      sym_number,
      sym_identifier,
    STATE(27), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [298] = 5,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(64), 2,
      sym_number,
      sym_identifier,
    STATE(47), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [322] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(66), 2,
      sym_number,
      sym_identifier,
    STATE(39), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [346] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_number,
      sym_identifier,
    STATE(33), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [370] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(70), 2,
      sym_number,
      sym_identifier,
    STATE(40), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [394] = 5,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(72), 2,
      sym_number,
      sym_identifier,
    STATE(45), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [418] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(74), 2,
      sym_number,
      sym_identifier,
    STATE(26), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [442] = 5,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(76), 2,
      sym_number,
      sym_identifier,
    STATE(43), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [466] = 5,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(78), 2,
      sym_number,
      sym_identifier,
    STATE(53), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [490] = 3,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_call_arguments,
    ACTIONS(82), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [507] = 2,
    ACTIONS(86), 3,
      anon_sym_fun,
      anon_sym_val,
      sym_identifier,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [521] = 1,
    ACTIONS(88), 9,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_DOT,
  [533] = 2,
    ACTIONS(86), 3,
      anon_sym_fun,
      anon_sym_val,
      sym_identifier,
    ACTIONS(84), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [547] = 1,
    ACTIONS(90), 9,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_DOT,
  [559] = 1,
    ACTIONS(92), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [570] = 1,
    ACTIONS(94), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [581] = 6,
    ACTIONS(96), 1,
      anon_sym_RPAREN,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    ACTIONS(104), 1,
      anon_sym_DOT,
    STATE(57), 1,
      aux_sym_call_arguments_repeat1,
    ACTIONS(98), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(100), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [602] = 3,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(100), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(106), 5,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [617] = 2,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(106), 7,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [630] = 7,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      sym_number,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      aux_sym_object_expression_repeat1,
    STATE(72), 1,
      sym_object_property,
    STATE(79), 2,
      sym_string,
      sym__property_key,
  [653] = 1,
    ACTIONS(114), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [664] = 1,
    ACTIONS(116), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [675] = 1,
    ACTIONS(118), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [686] = 1,
    ACTIONS(120), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [697] = 2,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(122), 7,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [710] = 1,
    ACTIONS(124), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [721] = 6,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_call_arguments_repeat1,
    ACTIONS(98), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(100), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [742] = 7,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      sym_number,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_object_expression_repeat1,
    STATE(63), 1,
      sym_object_property,
    STATE(79), 2,
      sym_string,
      sym__property_key,
  [765] = 4,
    ACTIONS(82), 1,
      anon_sym_LF,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    STATE(48), 1,
      sym_call_arguments,
    ACTIONS(132), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [782] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      sym_number,
    STATE(76), 1,
      sym_object_property,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(79), 2,
      sym_string,
      sym__property_key,
  [800] = 4,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(98), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(100), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(136), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [816] = 4,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(98), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(100), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(138), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [832] = 2,
    ACTIONS(114), 1,
      anon_sym_LF,
    ACTIONS(140), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [843] = 2,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(142), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [854] = 3,
    ACTIONS(106), 1,
      anon_sym_LF,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(144), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [867] = 4,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(148), 1,
      anon_sym_LF,
    ACTIONS(150), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(152), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [882] = 3,
    ACTIONS(122), 1,
      anon_sym_LF,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(154), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [895] = 2,
    ACTIONS(88), 1,
      anon_sym_LF,
    ACTIONS(156), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [906] = 4,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(158), 1,
      anon_sym_LF,
    ACTIONS(150), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(152), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [921] = 2,
    ACTIONS(116), 1,
      anon_sym_LF,
    ACTIONS(160), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [932] = 2,
    ACTIONS(92), 1,
      anon_sym_LF,
    ACTIONS(162), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [943] = 2,
    ACTIONS(118), 1,
      anon_sym_LF,
    ACTIONS(164), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [954] = 2,
    ACTIONS(90), 1,
      anon_sym_LF,
    ACTIONS(166), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [965] = 2,
    ACTIONS(94), 1,
      anon_sym_LF,
    ACTIONS(168), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [976] = 4,
    ACTIONS(106), 1,
      anon_sym_LF,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(144), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(152), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [991] = 2,
    ACTIONS(124), 1,
      anon_sym_LF,
    ACTIONS(170), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [1002] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_object_expression_repeat1,
  [1012] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_object_expression_repeat1,
  [1022] = 3,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_call_arguments_repeat1,
  [1032] = 3,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
    ACTIONS(180), 1,
      sym_unescaped_string_fragment,
    STATE(69), 1,
      aux_sym_string_repeat1,
  [1042] = 3,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_function_parameters_repeat1,
  [1052] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_object_expression_repeat1,
  [1062] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_object_expression_repeat1,
  [1072] = 3,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_call_arguments_repeat1,
  [1082] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_object_expression_repeat1,
  [1092] = 3,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_call_arguments_repeat1,
  [1102] = 3,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    ACTIONS(198), 1,
      sym_unescaped_string_fragment,
    STATE(71), 1,
      aux_sym_string_repeat1,
  [1112] = 3,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_object_expression_repeat1,
  [1122] = 3,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_function_parameters_repeat1,
  [1132] = 3,
    ACTIONS(209), 1,
      anon_sym_DQUOTE,
    ACTIONS(211), 1,
      sym_unescaped_string_fragment,
    STATE(65), 1,
      aux_sym_string_repeat1,
  [1142] = 3,
    ACTIONS(198), 1,
      sym_unescaped_string_fragment,
    ACTIONS(213), 1,
      anon_sym_DQUOTE,
    STATE(71), 1,
      aux_sym_string_repeat1,
  [1152] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_function_parameters_repeat1,
  [1162] = 3,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    ACTIONS(219), 1,
      sym_unescaped_string_fragment,
    STATE(71), 1,
      aux_sym_string_repeat1,
  [1172] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_object_expression_repeat1,
  [1182] = 2,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    ACTIONS(224), 1,
      sym_identifier,
  [1189] = 2,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    STATE(77), 1,
      sym_function_parameters,
  [1196] = 1,
    ACTIONS(182), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1201] = 1,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1206] = 2,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    STATE(84), 1,
      sym_block,
  [1213] = 1,
    ACTIONS(230), 1,
      anon_sym_EQ,
  [1217] = 1,
    ACTIONS(232), 1,
      anon_sym_COLON,
  [1221] = 1,
    ACTIONS(234), 1,
      sym_identifier,
  [1225] = 1,
    ACTIONS(236), 1,
      sym_identifier,
  [1229] = 1,
    ACTIONS(238), 1,
      sym_identifier,
  [1233] = 1,
    ACTIONS(240), 1,
      anon_sym_LBRACE,
  [1237] = 1,
    ACTIONS(242), 1,
      anon_sym_LF,
  [1241] = 1,
    ACTIONS(244), 1,
      sym_identifier,
  [1245] = 1,
    ACTIONS(246), 1,
      anon_sym_LF,
  [1249] = 1,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
  [1253] = 1,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
  [1257] = 1,
    ACTIONS(252), 1,
      sym_identifier,
  [1261] = 1,
    ACTIONS(254), 1,
      anon_sym_LF,
  [1265] = 1,
    ACTIONS(256), 1,
      anon_sym_LF,
  [1269] = 1,
    ACTIONS(258), 1,
      anon_sym_LF,
  [1273] = 1,
    ACTIONS(260), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 176,
  [SMALL_STATE(7)] = 220,
  [SMALL_STATE(8)] = 247,
  [SMALL_STATE(9)] = 274,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 322,
  [SMALL_STATE(12)] = 346,
  [SMALL_STATE(13)] = 370,
  [SMALL_STATE(14)] = 394,
  [SMALL_STATE(15)] = 418,
  [SMALL_STATE(16)] = 442,
  [SMALL_STATE(17)] = 466,
  [SMALL_STATE(18)] = 490,
  [SMALL_STATE(19)] = 507,
  [SMALL_STATE(20)] = 521,
  [SMALL_STATE(21)] = 533,
  [SMALL_STATE(22)] = 547,
  [SMALL_STATE(23)] = 559,
  [SMALL_STATE(24)] = 570,
  [SMALL_STATE(25)] = 581,
  [SMALL_STATE(26)] = 602,
  [SMALL_STATE(27)] = 617,
  [SMALL_STATE(28)] = 630,
  [SMALL_STATE(29)] = 653,
  [SMALL_STATE(30)] = 664,
  [SMALL_STATE(31)] = 675,
  [SMALL_STATE(32)] = 686,
  [SMALL_STATE(33)] = 697,
  [SMALL_STATE(34)] = 710,
  [SMALL_STATE(35)] = 721,
  [SMALL_STATE(36)] = 742,
  [SMALL_STATE(37)] = 765,
  [SMALL_STATE(38)] = 782,
  [SMALL_STATE(39)] = 800,
  [SMALL_STATE(40)] = 816,
  [SMALL_STATE(41)] = 832,
  [SMALL_STATE(42)] = 843,
  [SMALL_STATE(43)] = 854,
  [SMALL_STATE(44)] = 867,
  [SMALL_STATE(45)] = 882,
  [SMALL_STATE(46)] = 895,
  [SMALL_STATE(47)] = 906,
  [SMALL_STATE(48)] = 921,
  [SMALL_STATE(49)] = 932,
  [SMALL_STATE(50)] = 943,
  [SMALL_STATE(51)] = 954,
  [SMALL_STATE(52)] = 965,
  [SMALL_STATE(53)] = 976,
  [SMALL_STATE(54)] = 991,
  [SMALL_STATE(55)] = 1002,
  [SMALL_STATE(56)] = 1012,
  [SMALL_STATE(57)] = 1022,
  [SMALL_STATE(58)] = 1032,
  [SMALL_STATE(59)] = 1042,
  [SMALL_STATE(60)] = 1052,
  [SMALL_STATE(61)] = 1062,
  [SMALL_STATE(62)] = 1072,
  [SMALL_STATE(63)] = 1082,
  [SMALL_STATE(64)] = 1092,
  [SMALL_STATE(65)] = 1102,
  [SMALL_STATE(66)] = 1112,
  [SMALL_STATE(67)] = 1122,
  [SMALL_STATE(68)] = 1132,
  [SMALL_STATE(69)] = 1142,
  [SMALL_STATE(70)] = 1152,
  [SMALL_STATE(71)] = 1162,
  [SMALL_STATE(72)] = 1172,
  [SMALL_STATE(73)] = 1182,
  [SMALL_STATE(74)] = 1189,
  [SMALL_STATE(75)] = 1196,
  [SMALL_STATE(76)] = 1201,
  [SMALL_STATE(77)] = 1206,
  [SMALL_STATE(78)] = 1213,
  [SMALL_STATE(79)] = 1217,
  [SMALL_STATE(80)] = 1221,
  [SMALL_STATE(81)] = 1225,
  [SMALL_STATE(82)] = 1229,
  [SMALL_STATE(83)] = 1233,
  [SMALL_STATE(84)] = 1237,
  [SMALL_STATE(85)] = 1241,
  [SMALL_STATE(86)] = 1245,
  [SMALL_STATE(87)] = 1249,
  [SMALL_STATE(88)] = 1253,
  [SMALL_STATE(89)] = 1257,
  [SMALL_STATE(90)] = 1261,
  [SMALL_STATE(91)] = 1265,
  [SMALL_STATE(92)] = 1269,
  [SMALL_STATE(93)] = 1273,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(44),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(58),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(28),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(82),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(81),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(44),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, .production_id = 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_expression, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_expression, 3),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_expression, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, .production_id = 5),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expression, 3, .production_id = 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_expression_repeat1, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_arguments_repeat1, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_property, 3, .production_id = 4),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_expression, 4),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_arguments, 3),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, .production_id = 5),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_expression, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_arguments, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_expression, 3),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_arguments, 4),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_parameters_repeat1, 2),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_parameters_repeat1, 2), SHIFT_REPEAT(85),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_arguments_repeat1, 2), SHIFT_REPEAT(11),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_expression_repeat1, 2), SHIFT_REPEAT(38),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_expression_repeat1, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(71),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameters, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameters, 2),
  [250] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameters, 4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_bokunoscript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
