#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 6

enum {
  anon_sym_LF = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_PLUS = 4,
  anon_sym_DASH = 5,
  anon_sym_STAR = 6,
  anon_sym_SLASH = 7,
  sym_number = 8,
  anon_sym_DQUOTE = 9,
  sym_unescaped_string_fragment = 10,
  anon_sym_LBRACE = 11,
  anon_sym_COMMA = 12,
  anon_sym_RBRACE = 13,
  anon_sym_COLON = 14,
  anon_sym_DOT = 15,
  anon_sym_fun = 16,
  anon_sym_val = 17,
  anon_sym_EQ = 18,
  sym_identifier = 19,
  sym_source_file = 20,
  sym__statement = 21,
  sym_expression_statement = 22,
  sym__expression = 23,
  sym_unary_expression = 24,
  sym_binary_expression = 25,
  sym_string = 26,
  sym_object_expression = 27,
  sym_object_property = 28,
  sym__property_key = 29,
  sym_member_expression = 30,
  sym_call_expression = 31,
  sym_call_arguments = 32,
  sym_function_declaration = 33,
  sym_variable_declaration = 34,
  sym_block = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_string_repeat1 = 37,
  aux_sym_object_expression_repeat1 = 38,
  aux_sym_call_arguments_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_unescaped_string_fragment] = "unescaped_string_fragment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_fun] = "fun",
  [anon_sym_val] = "val",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_string] = "string",
  [sym_object_expression] = "object_expression",
  [sym_object_property] = "object_property",
  [sym__property_key] = "_property_key",
  [sym_member_expression] = "member_expression",
  [sym_call_expression] = "call_expression",
  [sym_call_arguments] = "call_arguments",
  [sym_function_declaration] = "function_declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym_block] = "block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_object_expression_repeat1] = "object_expression_repeat1",
  [aux_sym_call_arguments_repeat1] = "call_arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_unescaped_string_fragment] = sym_unescaped_string_fragment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_string] = sym_string,
  [sym_object_expression] = sym_object_expression,
  [sym_object_property] = sym_object_property,
  [sym__property_key] = sym__property_key,
  [sym_member_expression] = sym_member_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_call_arguments] = sym_call_arguments,
  [sym_function_declaration] = sym_function_declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_block] = sym_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_object_expression_repeat1] = aux_sym_object_expression_repeat1,
  [aux_sym_call_arguments_repeat1] = aux_sym_call_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_unescaped_string_fragment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_object_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_object_property] = {
    .visible = true,
    .named = true,
  },
  [sym__property_key] = {
    .visible = false,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_expr = 1,
  field_function = 2,
  field_key = 3,
  field_lhs = 4,
  field_object = 5,
  field_op = 6,
  field_property = 7,
  field_receiver = 8,
  field_rhs = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_expr] = "expr",
  [field_function] = "function",
  [field_key] = "key",
  [field_lhs] = "lhs",
  [field_object] = "object",
  [field_op] = "op",
  [field_property] = "property",
  [field_receiver] = "receiver",
  [field_rhs] = "rhs",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
  [4] = {.index = 7, .length = 2},
  [5] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expr, 1},
    {field_op, 0},
  [2] =
    {field_lhs, 0},
    {field_op, 1},
    {field_rhs, 2},
  [5] =
    {field_object, 0},
    {field_property, 2},
  [7] =
    {field_key, 0},
    {field_value, 2},
  [9] =
    {field_function, 2},
    {field_receiver, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 16,
  [17] = 10,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 20,
  [23] = 23,
  [24] = 18,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 25,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 34,
  [43] = 19,
  [44] = 33,
  [45] = 23,
  [46] = 31,
  [47] = 47,
  [48] = 30,
  [49] = 29,
  [50] = 35,
  [51] = 36,
  [52] = 32,
  [53] = 28,
  [54] = 21,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 56,
  [59] = 59,
  [60] = 60,
  [61] = 59,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 55,
  [66] = 60,
  [67] = 67,
  [68] = 63,
  [69] = 57,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 74,
  [80] = 75,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static inline bool sym_identifier_character_set_1(int32_t c) {
  return (c < 160
    ? (c < '['
      ? (c < 0
        ? c == 0
        : (c <= '#' || (c >= '%' && c <= '@')))
      : (c <= '^' || (c < '|'
        ? c == '`'
        : c <= '~')))
    : (c <= 160 || (c < 8287
      ? (c < 8192
        ? c == 5760
        : (c <= 8203 || c == 8239))
      : (c <= 8288 || (c < 65279
        ? c == 12288
        : c <= 65279)))));
}

static inline bool sym_identifier_character_set_2(int32_t c) {
  return (c < 160
    ? (c < ':'
      ? (c < 0
        ? c == 0
        : (c <= '#' || (c >= '%' && c <= '/')))
      : (c <= '@' || (c < '`'
        ? (c >= '[' && c <= '^')
        : (c <= '`' || (c >= '{' && c <= '~')))))
    : (c <= 160 || (c < 8287
      ? (c < 8192
        ? c == 5760
        : (c <= 8203 || c == 8239))
      : (c <= 8288 || (c < 65279
        ? c == 12288
        : c <= 65279)))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == ':') ADVANCE(26);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'f') ADVANCE(34);
      if (lookahead == 'v') ADVANCE(31);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (!sym_identifier_character_set_1(lookahead)) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (!sym_identifier_character_set_1(lookahead)) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '{') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_unescaped_string_fragment);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_unescaped_string_fragment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_fun);
      if (lookahead == '\\') ADVANCE(4);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_val);
      if (lookahead == '\\') ADVANCE(4);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'a') ADVANCE(32);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(29);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(28);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'u') ADVANCE(33);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(4);
      if (!sym_identifier_character_set_2(lookahead)) ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(83),
    [sym__statement] = STATE(2),
    [sym_expression_statement] = STATE(80),
    [sym__expression] = STATE(41),
    [sym_unary_expression] = STATE(41),
    [sym_binary_expression] = STATE(41),
    [sym_string] = STATE(41),
    [sym_object_expression] = STATE(41),
    [sym_member_expression] = STATE(41),
    [sym_call_expression] = STATE(41),
    [sym_function_declaration] = STATE(80),
    [sym_variable_declaration] = STATE(80),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_fun] = ACTIONS(13),
    [anon_sym_val] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
  [2] = {
    [sym__statement] = STATE(4),
    [sym_expression_statement] = STATE(80),
    [sym__expression] = STATE(41),
    [sym_unary_expression] = STATE(41),
    [sym_binary_expression] = STATE(41),
    [sym_string] = STATE(41),
    [sym_object_expression] = STATE(41),
    [sym_member_expression] = STATE(41),
    [sym_call_expression] = STATE(41),
    [sym_function_declaration] = STATE(80),
    [sym_variable_declaration] = STATE(80),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_fun] = ACTIONS(13),
    [anon_sym_val] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
  [3] = {
    [sym__statement] = STATE(5),
    [sym_expression_statement] = STATE(75),
    [sym__expression] = STATE(41),
    [sym_unary_expression] = STATE(41),
    [sym_binary_expression] = STATE(41),
    [sym_string] = STATE(41),
    [sym_object_expression] = STATE(41),
    [sym_member_expression] = STATE(41),
    [sym_call_expression] = STATE(41),
    [sym_function_declaration] = STATE(75),
    [sym_variable_declaration] = STATE(75),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_fun] = ACTIONS(13),
    [anon_sym_val] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
  [4] = {
    [sym__statement] = STATE(4),
    [sym_expression_statement] = STATE(80),
    [sym__expression] = STATE(41),
    [sym_unary_expression] = STATE(41),
    [sym_binary_expression] = STATE(41),
    [sym_string] = STATE(41),
    [sym_object_expression] = STATE(41),
    [sym_member_expression] = STATE(41),
    [sym_call_expression] = STATE(41),
    [sym_function_declaration] = STATE(80),
    [sym_variable_declaration] = STATE(80),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [sym_number] = ACTIONS(28),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(34),
    [anon_sym_fun] = ACTIONS(37),
    [anon_sym_val] = ACTIONS(40),
    [sym_identifier] = ACTIONS(43),
  },
  [5] = {
    [sym__statement] = STATE(6),
    [sym_expression_statement] = STATE(75),
    [sym__expression] = STATE(41),
    [sym_unary_expression] = STATE(41),
    [sym_binary_expression] = STATE(41),
    [sym_string] = STATE(41),
    [sym_object_expression] = STATE(41),
    [sym_member_expression] = STATE(41),
    [sym_call_expression] = STATE(41),
    [sym_function_declaration] = STATE(75),
    [sym_variable_declaration] = STATE(75),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(46),
    [anon_sym_fun] = ACTIONS(13),
    [anon_sym_val] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
  [6] = {
    [sym__statement] = STATE(6),
    [sym_expression_statement] = STATE(75),
    [sym__expression] = STATE(41),
    [sym_unary_expression] = STATE(41),
    [sym_binary_expression] = STATE(41),
    [sym_string] = STATE(41),
    [sym_object_expression] = STATE(41),
    [sym_member_expression] = STATE(41),
    [sym_call_expression] = STATE(41),
    [sym_function_declaration] = STATE(75),
    [sym_variable_declaration] = STATE(75),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [sym_number] = ACTIONS(28),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(34),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_fun] = ACTIONS(37),
    [anon_sym_val] = ACTIONS(40),
    [sym_identifier] = ACTIONS(43),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(48), 1,
      anon_sym_RPAREN,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(52), 2,
      sym_number,
      sym_identifier,
    STATE(37), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [27] = 6,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(60), 2,
      sym_number,
      sym_identifier,
    STATE(25), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [54] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(62), 2,
      sym_number,
      sym_identifier,
    STATE(33), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [78] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(64), 2,
      sym_number,
      sym_identifier,
    STATE(34), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [102] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(66), 2,
      sym_number,
      sym_identifier,
    STATE(39), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [126] = 5,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_number,
      sym_identifier,
    STATE(44), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [150] = 5,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(70), 2,
      sym_number,
      sym_identifier,
    STATE(51), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [174] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(72), 2,
      sym_number,
      sym_identifier,
    STATE(38), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [198] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(74), 2,
      sym_number,
      sym_identifier,
    STATE(36), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [222] = 5,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(76), 2,
      sym_number,
      sym_identifier,
    STATE(47), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [246] = 5,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(78), 2,
      sym_number,
      sym_identifier,
    STATE(42), 7,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_string,
      sym_object_expression,
      sym_member_expression,
      sym_call_expression,
  [270] = 3,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_call_arguments,
    ACTIONS(82), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [287] = 1,
    ACTIONS(84), 9,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_DOT,
  [299] = 2,
    ACTIONS(88), 3,
      anon_sym_fun,
      anon_sym_val,
      sym_identifier,
    ACTIONS(86), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [313] = 1,
    ACTIONS(90), 9,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_DOT,
  [325] = 2,
    ACTIONS(88), 3,
      anon_sym_fun,
      anon_sym_val,
      sym_identifier,
    ACTIONS(86), 6,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [339] = 1,
    ACTIONS(92), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [350] = 4,
    ACTIONS(82), 1,
      anon_sym_LF,
    ACTIONS(94), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_call_arguments,
    ACTIONS(96), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [367] = 6,
    ACTIONS(98), 1,
      anon_sym_RPAREN,
    ACTIONS(104), 1,
      anon_sym_COMMA,
    ACTIONS(106), 1,
      anon_sym_DOT,
    STATE(66), 1,
      aux_sym_call_arguments_repeat1,
    ACTIONS(100), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [388] = 7,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      sym_number,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      aux_sym_object_expression_repeat1,
    STATE(68), 1,
      sym_object_property,
    STATE(82), 2,
      sym_string,
      sym__property_key,
  [411] = 7,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      sym_number,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_object_expression_repeat1,
    STATE(63), 1,
      sym_object_property,
    STATE(82), 2,
      sym_string,
      sym__property_key,
  [434] = 1,
    ACTIONS(116), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [445] = 1,
    ACTIONS(118), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [456] = 1,
    ACTIONS(120), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [467] = 1,
    ACTIONS(122), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [478] = 1,
    ACTIONS(124), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [489] = 2,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(126), 7,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [502] = 3,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(126), 5,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [517] = 1,
    ACTIONS(128), 8,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [528] = 2,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(130), 7,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [541] = 6,
    ACTIONS(104), 1,
      anon_sym_COMMA,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_call_arguments_repeat1,
    ACTIONS(100), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [562] = 4,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(100), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [578] = 4,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(100), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(136), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [594] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      sym_number,
    STATE(71), 1,
      sym_object_property,
    ACTIONS(138), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(82), 2,
      sym_string,
      sym__property_key,
  [612] = 4,
    ACTIONS(140), 1,
      anon_sym_LF,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(142), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(144), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [627] = 4,
    ACTIONS(126), 1,
      anon_sym_LF,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(144), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [642] = 2,
    ACTIONS(84), 1,
      anon_sym_LF,
    ACTIONS(150), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [653] = 3,
    ACTIONS(126), 1,
      anon_sym_LF,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(148), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [666] = 2,
    ACTIONS(92), 1,
      anon_sym_LF,
    ACTIONS(152), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [677] = 2,
    ACTIONS(122), 1,
      anon_sym_LF,
    ACTIONS(154), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [688] = 4,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(156), 1,
      anon_sym_LF,
    ACTIONS(142), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(144), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [703] = 2,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(158), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [714] = 2,
    ACTIONS(118), 1,
      anon_sym_LF,
    ACTIONS(160), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [725] = 2,
    ACTIONS(128), 1,
      anon_sym_LF,
    ACTIONS(162), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [736] = 3,
    ACTIONS(130), 1,
      anon_sym_LF,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(164), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [749] = 2,
    ACTIONS(124), 1,
      anon_sym_LF,
    ACTIONS(166), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [760] = 2,
    ACTIONS(116), 1,
      anon_sym_LF,
    ACTIONS(168), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [771] = 2,
    ACTIONS(90), 1,
      anon_sym_LF,
    ACTIONS(170), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [782] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_object_expression_repeat1,
  [792] = 3,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      sym_unescaped_string_fragment,
    STATE(67), 1,
      aux_sym_string_repeat1,
  [802] = 3,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
    ACTIONS(180), 1,
      sym_unescaped_string_fragment,
    STATE(58), 1,
      aux_sym_string_repeat1,
  [812] = 3,
    ACTIONS(176), 1,
      sym_unescaped_string_fragment,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      aux_sym_string_repeat1,
  [822] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_object_expression_repeat1,
  [832] = 3,
    ACTIONS(104), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_call_arguments_repeat1,
  [842] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_object_expression_repeat1,
  [852] = 3,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_call_arguments_repeat1,
  [862] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_object_expression_repeat1,
  [872] = 3,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_object_expression_repeat1,
  [882] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_object_expression_repeat1,
  [892] = 3,
    ACTIONS(104), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_call_arguments_repeat1,
  [902] = 3,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      sym_unescaped_string_fragment,
    STATE(67), 1,
      aux_sym_string_repeat1,
  [912] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_object_expression_repeat1,
  [922] = 3,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    ACTIONS(209), 1,
      sym_unescaped_string_fragment,
    STATE(56), 1,
      aux_sym_string_repeat1,
  [932] = 2,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    STATE(78), 1,
      sym_block,
  [939] = 1,
    ACTIONS(196), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [944] = 1,
    ACTIONS(213), 1,
      anon_sym_LF,
  [948] = 1,
    ACTIONS(215), 1,
      sym_identifier,
  [952] = 1,
    ACTIONS(217), 1,
      sym_identifier,
  [956] = 1,
    ACTIONS(219), 1,
      anon_sym_LF,
  [960] = 1,
    ACTIONS(221), 1,
      sym_identifier,
  [964] = 1,
    ACTIONS(223), 1,
      anon_sym_LF,
  [968] = 1,
    ACTIONS(225), 1,
      anon_sym_LF,
  [972] = 1,
    ACTIONS(227), 1,
      sym_identifier,
  [976] = 1,
    ACTIONS(229), 1,
      anon_sym_LF,
  [980] = 1,
    ACTIONS(231), 1,
      anon_sym_EQ,
  [984] = 1,
    ACTIONS(233), 1,
      anon_sym_COLON,
  [988] = 1,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 27,
  [SMALL_STATE(9)] = 54,
  [SMALL_STATE(10)] = 78,
  [SMALL_STATE(11)] = 102,
  [SMALL_STATE(12)] = 126,
  [SMALL_STATE(13)] = 150,
  [SMALL_STATE(14)] = 174,
  [SMALL_STATE(15)] = 198,
  [SMALL_STATE(16)] = 222,
  [SMALL_STATE(17)] = 246,
  [SMALL_STATE(18)] = 270,
  [SMALL_STATE(19)] = 287,
  [SMALL_STATE(20)] = 299,
  [SMALL_STATE(21)] = 313,
  [SMALL_STATE(22)] = 325,
  [SMALL_STATE(23)] = 339,
  [SMALL_STATE(24)] = 350,
  [SMALL_STATE(25)] = 367,
  [SMALL_STATE(26)] = 388,
  [SMALL_STATE(27)] = 411,
  [SMALL_STATE(28)] = 434,
  [SMALL_STATE(29)] = 445,
  [SMALL_STATE(30)] = 456,
  [SMALL_STATE(31)] = 467,
  [SMALL_STATE(32)] = 478,
  [SMALL_STATE(33)] = 489,
  [SMALL_STATE(34)] = 502,
  [SMALL_STATE(35)] = 517,
  [SMALL_STATE(36)] = 528,
  [SMALL_STATE(37)] = 541,
  [SMALL_STATE(38)] = 562,
  [SMALL_STATE(39)] = 578,
  [SMALL_STATE(40)] = 594,
  [SMALL_STATE(41)] = 612,
  [SMALL_STATE(42)] = 627,
  [SMALL_STATE(43)] = 642,
  [SMALL_STATE(44)] = 653,
  [SMALL_STATE(45)] = 666,
  [SMALL_STATE(46)] = 677,
  [SMALL_STATE(47)] = 688,
  [SMALL_STATE(48)] = 703,
  [SMALL_STATE(49)] = 714,
  [SMALL_STATE(50)] = 725,
  [SMALL_STATE(51)] = 736,
  [SMALL_STATE(52)] = 749,
  [SMALL_STATE(53)] = 760,
  [SMALL_STATE(54)] = 771,
  [SMALL_STATE(55)] = 782,
  [SMALL_STATE(56)] = 792,
  [SMALL_STATE(57)] = 802,
  [SMALL_STATE(58)] = 812,
  [SMALL_STATE(59)] = 822,
  [SMALL_STATE(60)] = 832,
  [SMALL_STATE(61)] = 842,
  [SMALL_STATE(62)] = 852,
  [SMALL_STATE(63)] = 862,
  [SMALL_STATE(64)] = 872,
  [SMALL_STATE(65)] = 882,
  [SMALL_STATE(66)] = 892,
  [SMALL_STATE(67)] = 902,
  [SMALL_STATE(68)] = 912,
  [SMALL_STATE(69)] = 922,
  [SMALL_STATE(70)] = 932,
  [SMALL_STATE(71)] = 939,
  [SMALL_STATE(72)] = 944,
  [SMALL_STATE(73)] = 948,
  [SMALL_STATE(74)] = 952,
  [SMALL_STATE(75)] = 956,
  [SMALL_STATE(76)] = 960,
  [SMALL_STATE(77)] = 964,
  [SMALL_STATE(78)] = 968,
  [SMALL_STATE(79)] = 972,
  [SMALL_STATE(80)] = 976,
  [SMALL_STATE(81)] = 980,
  [SMALL_STATE(82)] = 984,
  [SMALL_STATE(83)] = 988,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(13),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(41),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(26),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(41),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, .production_id = 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_expression, 3),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expression, 3, .production_id = 3),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 2),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, .production_id = 5),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_expression, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_expression, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_property, 3, .production_id = 4),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_arguments_repeat1, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_expression_repeat1, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_expression, 3),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, .production_id = 5),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_arguments, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_arguments, 3),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_expression, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_expression, 4),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_arguments, 4),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_arguments_repeat1, 2), SHIFT_REPEAT(11),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_expression_repeat1, 2), SHIFT_REPEAT(40),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_expression_repeat1, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(67),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 3),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_bokunoscript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
